# Generated by Django 2.2 on 2020-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colexin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_color', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='colexin/')),
                ('logo_blanco', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='colexin/')),
                ('logo_gris', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='colexin/')),
                ('logo_negro', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='colexin/')),
                ('favicon', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='colexin/')),
            ],
            options={
                'verbose_name_plural': '1. Colexin',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': '7. Contácto',
            },
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '8. Contácto Redes Sociales',
            },
        ),
    ]
