# Generated by Django 2.2 on 2020-04-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aleacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aleacion', models.CharField(blank=True, max_length=8, null=True)),
                ('detalle', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Aleacion',
            },
        ),
        migrations.CreateModel(
            name='Anios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, help_text='Año', null=True)),
            ],
            options={
                'verbose_name_plural': '1. Años',
            },
        ),
        migrations.CreateModel(
            name='Cecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceca', models.CharField(blank=True, max_length=90, null=True)),
                ('marca_ceca', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Ceca',
            },
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continente', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Continente',
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.CharField(blank=True, max_length=8, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=90, null=True)),
                ('image_a', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='products/')),
                ('image_b', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='products/')),
            ],
            options={
                'verbose_name_plural': '6. Denominacion',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Motivo',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=90, null=True)),
                ('continente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Continente')),
            ],
            options={
                'verbose_name_plural': '2. Pais',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=90, null=True)),
                ('image_a', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='products/')),
                ('image_b', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='products/')),
                ('anio_inicio', models.CharField(blank=True, max_length=90, null=True)),
                ('anio_fin', models.CharField(blank=True, max_length=90, null=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Pais')),
            ],
            options={
                'verbose_name_plural': '3. Periodo',
            },
        ),
        migrations.CreateModel(
            name='Sistema_monetario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acunacion', models.IntegerField(blank=True, null=True)),
                ('PROOF', models.IntegerField(blank=True, help_text='Prueba', null=True)),
                ('MS', models.IntegerField(blank=True, help_text='Flor De Cuño', null=True)),
                ('UNC', models.IntegerField(blank=True, help_text='Sin Circula', null=True)),
                ('XF', models.IntegerField(blank=True, help_text='Excelente Bien Conservada', null=True)),
                ('VF', models.IntegerField(blank=True, help_text='Muy Bien Conservada', null=True)),
                ('F', models.IntegerField(blank=True, help_text='Mas que Bien Conservada', null=True)),
                ('VG', models.IntegerField(blank=True, help_text='Bien Conservada', null=True)),
                ('G', models.IntegerField(blank=True, help_text='Regular Conservación', null=True)),
                ('P', models.IntegerField(blank=True, help_text='Mal Conservada', null=True)),
                ('anio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Anios')),
                ('ceca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Cecas')),
                ('denomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Denominacion')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Periodo')),
            ],
            options={
                'verbose_name_plural': '7. Sistema Monetario',
            },
        ),
        migrations.AddField(
            model_name='denominacion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Periodo'),
        ),
        migrations.CreateModel(
            name='Denimina_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.CharField(blank=True, max_length=90, null=True)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('grosor', models.CharField(blank=True, max_length=10, null=True)),
                ('canto', models.CharField(blank=True, max_length=90, null=True)),
                ('diseniador', models.CharField(blank=True, max_length=50, null=True)),
                ('anverso', models.CharField(blank=True, max_length=90, null=True)),
                ('inverso', models.CharField(blank=True, max_length=90, null=True)),
                ('denominacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Denominacion')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Aleacion')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Motivo')),
            ],
            options={
                'verbose_name_plural': '6. Denimina_detalle',
            },
        ),
        migrations.AddField(
            model_name='cecas',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Pais'),
        ),
    ]
