# Generated by Django 2.2 on 2020-04-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleacion',
            name='aleacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aleacion',
            name='detalle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
