# Generated by Django 2.2 on 2020-05-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0003_denominacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominacion',
            name='anverso',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='canto',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='diametro',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='diseniador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='grosor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='inverso',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Aleacion'),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Motivo'),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='nota',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
