# Generated by Django 2.2 on 2020-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0004_auto_20200517_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='nota',
            field=models.TextField(blank=True, max_length=90, null=True),
        ),
    ]
