# Generated by Django 2.2 on 2020-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0005_auto_20200518_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='nota',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
