# Generated by Django 2.2 on 2020-04-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('articulo', models.TextField(blank=True, max_length=10000, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('tipo_imagen', models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='blog/')),
                ('tipo_video_link', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Blogs',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Categorias',
            },
        ),
        migrations.CreateModel(
            name='Visitas_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField(default=1)),
                ('blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs')),
            ],
            options={
                'verbose_name_plural': '4. Visitas al Blog',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Categoria'),
        ),
    ]
