# Generated by Django 2.2 on 2020-04-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Moneda', 'Moneda'), ('Billete', 'Billete'), ('Medalla', 'Medalla')], default='Moneda', max_length=60),
        ),
    ]
