# Generated by Django 2.2 on 2020-04-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Moneda', 'Moneda'), ('Billete', 'Billete'), ('Medalla', 'Medalla')], max_length=60),
        ),
    ]
