# Generated by Django 2.2 on 2020-04-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
