# Generated by Django 2.2 on 2020-05-06 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0002_auto_20200504_2248'),
        ('orders', '0006_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codes.PromoCode'),
        ),
    ]
