# Generated by Django 2.2 on 2020-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200425_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ceca',
        ),
        migrations.AddField(
            model_name='product',
            name='pais',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
