# Generated by Django 2.2 on 2020-04-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0001_initial'),
        ('products', '0005_auto_20200425_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ceca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Cecas'),
        ),
    ]
