# Generated by Django 2.2 on 2020-04-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0001_initial'),
        ('products', '0006_product_ceca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Aleacion'),
        ),
    ]
