# Generated by Django 2.2 on 2020-04-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_metal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ceca',
        ),
    ]
