# Generated by Django 2.2 on 2020-04-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200425_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pais',
        ),
    ]
