# Generated by Django 2.2 on 2020-04-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pais.Pais'),
        ),
    ]
