# Generated by Django 2.2 on 2020-04-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200425_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Moneda', 'Moneda'), ('Billete', 'Billete'), ('Medalla', 'Medalla')], default='Moneda', max_length=60, null=True),
        ),
    ]
