# Generated by Django 2.2 on 2020-04-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200426_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('Moneda', 'Moneda'), ('Billete', 'Billete'), ('Medalla', 'Medalla')], max_length=60),
        ),
    ]
