# Generated by Django 2.2 on 2020-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200426_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precio_oferta',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
