# Generated by Django 2.2 on 2020-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200510_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='precio_oferta',
        ),
    ]
