# Generated by Django 2.2 on 2020-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200510_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='UNC',
            field=models.IntegerField(blank=True, help_text='Sin Circular   ', null=True),
        ),
    ]
